# Configuration file for ccAutomator
# Lines starting with # are comments and will be ignored

# Priming configuration
--prime-file
prime.txt

# Card Conjurer Server
--url
http://mtgproxy:4242/

# Image server configuration
--image-server
http://mtgproxy:4242
--upload-path
/local_art/card_images/ccAutomator/

# Upscaling settings
--upscale-art
--ilaria-url
http://172.17.1.217:7860

# Visual options
--frame
Seventh
--white-border
--autofit-art

# Title formatting
--title-up
9
--title-font-size
4
--title-left
40
--title-kerning
4
--title-shadow
5

# Type line formatting
--auto-fit-type
--type-left
40
--type-kerning
3

# Power/Toughness formatting
--pt-kerning
7
--pt-font-size
45
--pt-shadow
6

# Rules text formatting
--hide-reminder-text
--rules-bounds-y
13
--rules-bounds-height
-26
--flavor-font
-15

# Card selection strategy
--card-selection
scryfall
--set-selection
all
--no-match-selection
random

# Set filtering
# Basic
#--include-set
#4ed
#--exclude-set
#30a,sld,pblb  # Exclude anniversary, secret lair, and bloomburrow

# Granular
#--spells-include-set
#blb,blc
#--spells-exclude-set
#tmt,tla,spm,mar,eoe,j25
#--basic-land-include-set
#--basic-land-exclude-set

# Additioanl Scryfall query modifiers
#--scryfall-filter
#"-is:ub"
